/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import javax.swing.WindowConstants;

/**
 *
 * @author Lorenzo Greco
 */
public class Calculadora extends javax.swing.JFrame {

    private int monto = 0;
    private float iva = 0;
    private float resultado = 0;
    private float resultadoConIva = 0;

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.setResizable(false);
        TextoResultadoTotal.setVisible(false);
        TextoResultadoTotalIngresar.setVisible(false);
        MontoIngresado.setVisible(false);
        TextoMontoFinalizado.setVisible(false);
        TextoAnteResultado.setVisible(false);
        TextoResultado.setVisible(false);
        GrupoBotones.add(opc_1);
        GrupoBotones.add(opc_2);
        GrupoBotones.add(opc_3);
        GrupoBotones.add(opc_4);
        GrupoBotones.add(opc_5);
        GrupoBotones.add(opc_6);
        GrupoBotones.add(opc_7);
        GrupoBotones.add(opc_8);
        GrupoBotones.add(opc_9);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBotones = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        opc_1 = new javax.swing.JRadioButton();
        opc_2 = new javax.swing.JRadioButton();
        opc_3 = new javax.swing.JRadioButton();
        opc_4 = new javax.swing.JRadioButton();
        opc_5 = new javax.swing.JRadioButton();
        opc_6 = new javax.swing.JRadioButton();
        opc_7 = new javax.swing.JRadioButton();
        opc_8 = new javax.swing.JRadioButton();
        opc_9 = new javax.swing.JRadioButton();
        TextoMonto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        TextoAyuda = new javax.swing.JLabel();
        TextoAnteResultado = new javax.swing.JLabel();
        TextoResultado = new javax.swing.JLabel();
        MontoIngresado = new javax.swing.JLabel();
        TextoMontoFinalizado = new javax.swing.JLabel();
        TextoResultadoTotal = new javax.swing.JLabel();
        TextoResultadoTotalIngresar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Calculadora de Envios");

        opc_1.setText("Catamarca");
        opc_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc_1ActionPerformed(evt);
            }
        });

        opc_2.setText("Mendoza");

        opc_3.setText("Tucuman");
        opc_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc_3ActionPerformed(evt);
            }
        });

        opc_4.setText("Santa Fe");

        opc_5.setText("Santiago del Estero");

        opc_6.setText("Entre Rios");

        opc_7.setText("La Pampa");

        opc_8.setText("Cordoba");

        opc_9.setText("Neuquen");
        opc_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc_9ActionPerformed(evt);
            }
        });

        TextoMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoMontoActionPerformed(evt);
            }
        });

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TextoAyuda.setText("Ingresar el monto total");

        TextoAnteResultado.setText("El resultado del IVA es:");

        TextoResultado.setText("jLabel4");

        MontoIngresado.setText("El monto ingresado es:");

        TextoMontoFinalizado.setText("jLabel4");

        TextoResultadoTotal.setText("El Resultado total es:");

        TextoResultadoTotalIngresar.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jLabel1))
                            .addComponent(opc_2)
                            .addComponent(opc_1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opc_3)
                                    .addComponent(opc_4)
                                    .addComponent(opc_5)
                                    .addComponent(opc_6)
                                    .addComponent(opc_7)
                                    .addComponent(opc_8))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TextoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1))
                                    .addComponent(TextoAyuda)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TextoAnteResultado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TextoResultado))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(MontoIngresado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TextoMontoFinalizado))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TextoResultadoTotal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TextoResultadoTotalIngresar)))))
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(opc_9)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(opc_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opc_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(TextoAyuda)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MontoIngresado)
                            .addComponent(TextoMontoFinalizado))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoAnteResultado)
                            .addComponent(TextoResultado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoResultadoTotal)
                            .addComponent(TextoResultadoTotalIngresar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(opc_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opc_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opc_5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opc_6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opc_7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opc_8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opc_9)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opc_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opc_1ActionPerformed

    private void TextoMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoMontoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

            String numerito = "";
            monto = Integer.parseInt(TextoMonto.getText());

            if (opc_1.isSelected()) { //Catamarca
                iva = (float) 2.5;
                CalculosDel80OP();
            }
            if (opc_2.isSelected()) {
                iva = (float) 4.25;
                CalculosOP();
            }
            if (opc_3.isSelected()) {
                iva = (float) 3.5;
                CalculosOP();
            }
            if (opc_4.isSelected()) {
                iva = (float) 3;
                CalculosOP();
            }
            if (opc_5.isSelected()) {
                iva = (float) 3;
                CalculosOP();
            }
            if (opc_6.isSelected()) {
                iva = (float) 6;
                CalculosOP();
            }
            if (opc_7.isSelected()) {
                iva = (float) 5;
                CalculosOP();
            }
            if (opc_8.isSelected()) {
                iva = (float) 2.5;
                CalculosDel80OP();
            }
            if (opc_9.isSelected()) {
                iva = (float) 5;
                CalculosOP();
            }

            if (resultado != 0) {
                TextoAnteResultado.setVisible(true);
                TextoResultado.setVisible(true);
                MontoIngresado.setVisible(true);
                TextoMontoFinalizado.setVisible(true);
                TextoResultadoTotal.setVisible(true);
                TextoResultadoTotalIngresar.setVisible(true);

                String ResultadoString = "";
                ResultadoString = Float.toString(resultado);
                TextoResultado.setText(ResultadoString);

                ResultadoString = Float.toString(monto);
                TextoMontoFinalizado.setText(ResultadoString);

                ResultadoString = Float.toString(resultadoConIva);
                TextoResultadoTotalIngresar.setText(ResultadoString);
                
            } else {
                MontoIngresado.setVisible(false);
                TextoMontoFinalizado.setVisible(false);
                TextoAnteResultado.setVisible(false);
                TextoResultado.setVisible(false);
                TextoResultadoTotal.setVisible(false);
        TextoResultadoTotalIngresar.setVisible(false);
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void opc_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opc_3ActionPerformed

    private void opc_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opc_9ActionPerformed
    private void CalculosOP() {
        float valorIntermedio = 0;
        valorIntermedio = monto * iva;
        resultado = valorIntermedio / 100;
        resultadoConIva = resultado + monto;
    }

    private void CalculosDel80OP() {
        float valorIntermedio = 0;
        valorIntermedio = monto * 80;
        valorIntermedio = valorIntermedio / 100;
        valorIntermedio = valorIntermedio * iva;
        resultado = valorIntermedio / 100;
        resultadoConIva = resultado + monto;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoBotones;
    private javax.swing.JLabel MontoIngresado;
    private javax.swing.JLabel TextoAnteResultado;
    private javax.swing.JLabel TextoAyuda;
    private javax.swing.JTextField TextoMonto;
    private javax.swing.JLabel TextoMontoFinalizado;
    private javax.swing.JLabel TextoResultado;
    private javax.swing.JLabel TextoResultadoTotal;
    private javax.swing.JLabel TextoResultadoTotalIngresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton opc_1;
    private javax.swing.JRadioButton opc_2;
    private javax.swing.JRadioButton opc_3;
    private javax.swing.JRadioButton opc_4;
    private javax.swing.JRadioButton opc_5;
    private javax.swing.JRadioButton opc_6;
    private javax.swing.JRadioButton opc_7;
    private javax.swing.JRadioButton opc_8;
    private javax.swing.JRadioButton opc_9;
    // End of variables declaration//GEN-END:variables
}
